// ACCIONES INICIO
export const SET_MOVIE_DATA = "SET_MOVIE_DATA";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_PAGE_SUCCESS = "CHANGE_PAGE_SUCCESS";
export const FETCH_NEW_MOVIES = "FETCH_NEW_MOVIES";

// ACCIONES LAYOUT
export const SEARCH_MOVIE_START = "SEARCH_MOVIE_START";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const RESTART_SEARCH_VALUES = "RESTART_SEARCH_VALUES";

// ACCIONES InfoPelicula
export const FETCH_INFO_INIT = "FETCH_INFO_INIT";
export const FETCH_INFO_SUCCESS = "FETCH_INFO_SUCCESS";

// ACCIONES MovieReviews
export const FETCH_REVIEWS_INIT = "FETCH_REVIEWS_INIT";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_ERROR = "FETCH_REVIEWS_ERROR";